export type SystemRole =
  | 'SUPER_ADMIN'
  | 'ADMIN'
  | 'MANAGER'
  | 'SUPERVISOR'
  | 'STAFF'
  | 'CASHIER'
  | 'INVENTORY_STAFF';

export const ROLES: Record<SystemRole, SystemRole> = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  ADMIN: 'ADMIN',
  MANAGER: 'MANAGER',
  SUPERVISOR: 'SUPERVISOR',
  STAFF: 'STAFF',
  CASHIER: 'CASHIER',
  INVENTORY_STAFF: 'INVENTORY_STAFF',
};

export const PERMISSIONS = {
  // Authentication & Profile
  AUTH_LOGIN: 'AUTH_LOGIN',
  PROFILE_VIEW: 'PROFILE_VIEW',
  PROFILE_EDIT: 'PROFILE_EDIT',

  // Staff & HR
  STAFF_VIEW: 'STAFF_VIEW',
  STAFF_MANAGE: 'STAFF_MANAGE',
  ATTENDANCE_VIEW: 'ATTENDANCE_VIEW',
  ATTENDANCE_CHECKIN: 'ATTENDANCE_CHECKIN',
  ATTENDANCE_MANAGE: 'ATTENDANCE_MANAGE',
  LEAVE_VIEW: 'LEAVE_VIEW',
  LEAVE_APPLY: 'LEAVE_APPLY',
  LEAVE_APPROVE: 'LEAVE_APPROVE',
  PAYROLL_VIEW: 'PAYROLL_VIEW',
  PAYROLL_MANAGE: 'PAYROLL_MANAGE',

  // POS & Sales Operations
  POS_VIEW: 'POS_VIEW',
  POS_CREATE_SALE: 'POS_CREATE_SALE',
  POS_APPLY_DISCOUNT: 'POS_APPLY_DISCOUNT',
  POS_HOLD_SALE: 'POS_HOLD_SALE',
  POS_PROCESS_RETURN: 'POS_PROCESS_RETURN',
  SALES_VIEW: 'SALES_VIEW',
  SALES_VIEW_ALL: 'SALES_VIEW_ALL',

  // Customers & Loyalty
  CUSTOMER_VIEW: 'CUSTOMER_VIEW',
  CUSTOMER_CREATE: 'CUSTOMER_CREATE',
  CUSTOMER_EDIT: 'CUSTOMER_EDIT',
  CUSTOMER_LOYALTY_ADJUST: 'CUSTOMER_LOYALTY_ADJUST',

  // Products & Inventory
  PRODUCT_VIEW: 'PRODUCT_VIEW',
  PRODUCT_MANAGE: 'PRODUCT_MANAGE',
  INVENTORY_VIEW: 'INVENTORY_VIEW',
  INVENTORY_COUNT: 'INVENTORY_COUNT',
  INVENTORY_ADJUST: 'INVENTORY_ADJUST',
  INVENTORY_TRANSFER: 'INVENTORY_TRANSFER',

  // Reports & Analytics
  REPORT_VIEW_PERSONAL: 'REPORT_VIEW_PERSONAL',
  REPORT_VIEW_ALL: 'REPORT_VIEW_ALL',
  REPORT_EXPORT: 'REPORT_EXPORT',

  // Settings & System
  SETTINGS_VIEW: 'SETTINGS_VIEW',
  SETTINGS_MANAGE: 'SETTINGS_MANAGE',
  NOTIFICATIONS_VIEW: 'NOTIFICATIONS_VIEW',
} as const;

export type PermissionKey = keyof typeof PERMISSIONS;
export type PermissionValue = typeof PERMISSIONS[PermissionKey];

/**
 * Default standard permission grants by role
 */
export const DEFAULT_ROLE_PERMISSIONS: Record<SystemRole, PermissionValue[]> = {
  SUPER_ADMIN: Object.values(PERMISSIONS),
  ADMIN: Object.values(PERMISSIONS),
  MANAGER: [
    PERMISSIONS.AUTH_LOGIN,
    PERMISSIONS.PROFILE_VIEW,
    PERMISSIONS.PROFILE_EDIT,
    PERMISSIONS.STAFF_VIEW,
    PERMISSIONS.ATTENDANCE_VIEW,
    PERMISSIONS.ATTENDANCE_CHECKIN,
    PERMISSIONS.ATTENDANCE_MANAGE,
    PERMISSIONS.LEAVE_VIEW,
    PERMISSIONS.LEAVE_APPLY,
    PERMISSIONS.LEAVE_APPROVE,
    PERMISSIONS.PAYROLL_VIEW,
    PERMISSIONS.POS_VIEW,
    PERMISSIONS.POS_CREATE_SALE,
    PERMISSIONS.POS_APPLY_DISCOUNT,
    PERMISSIONS.POS_HOLD_SALE,
    PERMISSIONS.POS_PROCESS_RETURN,
    PERMISSIONS.SALES_VIEW,
    PERMISSIONS.SALES_VIEW_ALL,
    PERMISSIONS.CUSTOMER_VIEW,
    PERMISSIONS.CUSTOMER_CREATE,
    PERMISSIONS.CUSTOMER_EDIT,
    PERMISSIONS.CUSTOMER_LOYALTY_ADJUST,
    PERMISSIONS.PRODUCT_VIEW,
    PERMISSIONS.PRODUCT_MANAGE,
    PERMISSIONS.INVENTORY_VIEW,
    PERMISSIONS.INVENTORY_COUNT,
    PERMISSIONS.INVENTORY_ADJUST,
    PERMISSIONS.INVENTORY_TRANSFER,
    PERMISSIONS.REPORT_VIEW_PERSONAL,
    PERMISSIONS.REPORT_VIEW_ALL,
    PERMISSIONS.REPORT_EXPORT,
    PERMISSIONS.SETTINGS_VIEW,
    PERMISSIONS.NOTIFICATIONS_VIEW,
  ],
  SUPERVISOR: [
    PERMISSIONS.AUTH_LOGIN,
    PERMISSIONS.PROFILE_VIEW,
    PERMISSIONS.ATTENDANCE_VIEW,
    PERMISSIONS.ATTENDANCE_CHECKIN,
    PERMISSIONS.LEAVE_VIEW,
    PERMISSIONS.LEAVE_APPLY,
    PERMISSIONS.PAYROLL_VIEW,
    PERMISSIONS.POS_VIEW,
    PERMISSIONS.POS_CREATE_SALE,
    PERMISSIONS.POS_APPLY_DISCOUNT,
    PERMISSIONS.POS_HOLD_SALE,
    PERMISSIONS.POS_PROCESS_RETURN,
    PERMISSIONS.SALES_VIEW,
    PERMISSIONS.CUSTOMER_VIEW,
    PERMISSIONS.CUSTOMER_CREATE,
    PERMISSIONS.CUSTOMER_EDIT,
    PERMISSIONS.PRODUCT_VIEW,
    PERMISSIONS.INVENTORY_VIEW,
    PERMISSIONS.INVENTORY_COUNT,
    PERMISSIONS.INVENTORY_TRANSFER,
    PERMISSIONS.REPORT_VIEW_PERSONAL,
    PERMISSIONS.NOTIFICATIONS_VIEW,
  ],
  STAFF: [
    PERMISSIONS.AUTH_LOGIN,
    PERMISSIONS.PROFILE_VIEW,
    PERMISSIONS.ATTENDANCE_VIEW,
    PERMISSIONS.ATTENDANCE_CHECKIN,
    PERMISSIONS.LEAVE_VIEW,
    PERMISSIONS.LEAVE_APPLY,
    PERMISSIONS.PAYROLL_VIEW,
    PERMISSIONS.POS_VIEW,
    PERMISSIONS.POS_CREATE_SALE,
    PERMISSIONS.POS_HOLD_SALE,
    PERMISSIONS.SALES_VIEW,
    PERMISSIONS.CUSTOMER_VIEW,
    PERMISSIONS.CUSTOMER_CREATE,
    PERMISSIONS.PRODUCT_VIEW,
    PERMISSIONS.INVENTORY_VIEW,
    PERMISSIONS.INVENTORY_COUNT,
    PERMISSIONS.REPORT_VIEW_PERSONAL,
    PERMISSIONS.NOTIFICATIONS_VIEW,
  ],
  CASHIER: [
    PERMISSIONS.AUTH_LOGIN,
    PERMISSIONS.PROFILE_VIEW,
    PERMISSIONS.ATTENDANCE_CHECKIN,
    PERMISSIONS.POS_VIEW,
    PERMISSIONS.POS_CREATE_SALE,
    PERMISSIONS.POS_HOLD_SALE,
    PERMISSIONS.POS_PROCESS_RETURN,
    PERMISSIONS.SALES_VIEW,
    PERMISSIONS.CUSTOMER_VIEW,
    PERMISSIONS.CUSTOMER_CREATE,
    PERMISSIONS.PRODUCT_VIEW,
    PERMISSIONS.REPORT_VIEW_PERSONAL,
    PERMISSIONS.NOTIFICATIONS_VIEW,
  ],
  INVENTORY_STAFF: [
    PERMISSIONS.AUTH_LOGIN,
    PERMISSIONS.PROFILE_VIEW,
    PERMISSIONS.ATTENDANCE_CHECKIN,
    PERMISSIONS.PRODUCT_VIEW,
    PERMISSIONS.INVENTORY_VIEW,
    PERMISSIONS.INVENTORY_COUNT,
    PERMISSIONS.INVENTORY_ADJUST,
    PERMISSIONS.INVENTORY_TRANSFER,
    PERMISSIONS.NOTIFICATIONS_VIEW,
  ],
};

/**
 * Check if a user's permission set includes a specific permission
 */
export function hasPermission(userPermissions: string[] | undefined, permission: string): boolean {
  if (!userPermissions || !Array.isArray(userPermissions)) return false;
  if (userPermissions.includes('*') || userPermissions.includes('SUPER_ADMIN')) return true;
  return userPermissions.includes(permission);
}

/**
 * Check if a user has ANY of the required permissions
 */
export function hasAnyPermission(userPermissions: string[] | undefined, permissions: string[]): boolean {
  if (!userPermissions || !Array.isArray(userPermissions)) return false;
  if (userPermissions.includes('*') || userPermissions.includes('SUPER_ADMIN')) return true;
  return permissions.some((p) => userPermissions.includes(p));
}

/**
 * Check if a user has ALL of the required permissions
 */
export function hasAllPermissions(userPermissions: string[] | undefined, permissions: string[]): boolean {
  if (!userPermissions || !Array.isArray(userPermissions)) return false;
  if (userPermissions.includes('*') || userPermissions.includes('SUPER_ADMIN')) return true;
  return permissions.every((p) => userPermissions.includes(p));
}

/**
 * Check if a user matches one of the specified roles
 */
export function hasRole(userRole: string | undefined, allowedRoles: string[]): boolean {
  if (!userRole) return false;
  if (userRole.toUpperCase() === 'SUPER_ADMIN') return true;
  return allowedRoles.map((r) => r.toUpperCase()).includes(userRole.toUpperCase());
}
