/**
 * Central Permission Catalog & Security Taxonomy
 * Single source of truth for Role-Based Access Control (RBAC) & Data Scoping.
 */

export type DataScope = 'GLOBAL' | 'BRANCH' | 'DEPARTMENT' | 'ASSIGNED' | 'SELF';

export interface PermissionDefinition {
  code: string;
  module: string;
  name: string;
  description: string;
  defaultRoles: ('ADMIN' | 'MANAGER' | 'SUPERVISOR' | 'CASHIER' | 'STAFF')[];
}

export const PERMISSION_CATALOG: PermissionDefinition[] = [
  // --- 1. DASHBOARD & FINANCIALS ---
  {
    code: 'DASHBOARD_EXECUTIVE_VIEW',
    module: 'Dashboard',
    name: 'View Executive Dashboard',
    description: 'Access company-wide executive business dashboard with full financial metrics and AI risk monitor.',
    defaultRoles: ['ADMIN'],
  },
  {
    code: 'DASHBOARD_MANAGEMENT_VIEW',
    module: 'Dashboard',
    name: 'View Management Dashboard',
    description: 'Access management dashboard with sales performance, branch revenue, and reorder forecasting.',
    defaultRoles: ['ADMIN', 'MANAGER'],
  },
  {
    code: 'DASHBOARD_OPERATIONS_VIEW',
    module: 'Dashboard',
    name: 'View Operations Dashboard',
    description: 'Access operations dashboard with floor stock levels, shift roster, and task progress.',
    defaultRoles: ['ADMIN', 'MANAGER', 'SUPERVISOR'],
  },
  {
    code: 'DASHBOARD_BILLING_VIEW',
    module: 'Dashboard',
    name: 'View Billing Dashboard',
    description: 'Access cashier billing dashboard with shift register balance and shortcut guides.',
    defaultRoles: ['ADMIN', 'MANAGER', 'SUPERVISOR', 'CASHIER'],
  },
  {
    code: 'DASHBOARD_WORK_VIEW',
    module: 'Dashboard',
    name: 'View Personal Work Dashboard',
    description: 'Access personal work dashboard with assigned tasks, shift schedule, and self-service tools.',
    defaultRoles: ['ADMIN', 'MANAGER', 'SUPERVISOR', 'CASHIER', 'STAFF'],
  },
  {
    code: 'FINANCIAL_METRICS_VIEW',
    module: 'Financials',
    name: 'View Financial Metrics',
    description: 'View sensitive company profit margins, gross profit, cash flow, and cost valuations.',
    defaultRoles: ['ADMIN'],
  },

  // --- 2. POS BILLING ---
  {
    code: 'POS_VIEW',
    module: 'Billing',
    name: 'Access POS Terminal',
    description: 'Open and operate POS billing terminal.',
    defaultRoles: ['ADMIN', 'MANAGER', 'SUPERVISOR', 'CASHIER'],
  },
  {
    code: 'POS_CREATE_SALE',
    module: 'Billing',
    name: 'Create POS Sale',
    description: 'Create and process customer checkout invoices.',
    defaultRoles: ['ADMIN', 'MANAGER', 'SUPERVISOR', 'CASHIER'],
  },
  {
    code: 'POS_APPLY_DISCOUNT',
    module: 'Billing',
    name: 'Apply Standard Discount',
    description: 'Apply standard bill discounts up to 5%.',
    defaultRoles: ['ADMIN', 'MANAGER', 'SUPERVISOR', 'CASHIER'],
  },
  {
    code: 'POS_APPLY_MANAGER_DISCOUNT',
    module: 'Billing',
    name: 'Authorize High Discount',
    description: 'Authorize bill discounts greater than 5% (up to 20%).',
    defaultRoles: ['ADMIN', 'MANAGER'],
  },

  // --- 3. SALES & TRANSACTIONS ---
  {
    code: 'SALES_VIEW_ALL',
    module: 'Sales',
    name: 'View All Sales History',
    description: 'View store-wide and company-wide historical sales invoices.',
    defaultRoles: ['ADMIN', 'MANAGER'],
  },
  {
    code: 'SALES_VIEW_SELF',
    module: 'Sales',
    name: 'View Personal Sales History',
    description: 'View sales invoices generated by current user/terminal.',
    defaultRoles: ['ADMIN', 'MANAGER', 'SUPERVISOR', 'CASHIER'],
  },
  {
    code: 'SALES_CANCEL',
    module: 'Sales',
    name: 'Cancel Sales Invoice',
    description: 'Void and cancel finalized sales invoice and restore stock.',
    defaultRoles: ['ADMIN', 'MANAGER'],
  },
  {
    code: 'SALES_EXPORT',
    module: 'Sales',
    name: 'Export Sales History',
    description: 'Export sales reports and invoice lists to Excel or CSV.',
    defaultRoles: ['ADMIN', 'MANAGER'],
  },

  // --- 4. RETURNS & EXCHANGES ---
  {
    code: 'RETURN_CREATE',
    module: 'Returns',
    name: 'Create Sales Return',
    description: 'Initiate return or exchange of customer purchased items.',
    defaultRoles: ['ADMIN', 'MANAGER', 'SUPERVISOR', 'CASHIER'],
  },
  {
    code: 'RETURN_APPROVE',
    module: 'Returns',
    name: 'Approve Sales Return',
    description: 'Authorize product return and initiate cash/credit refund.',
    defaultRoles: ['ADMIN', 'MANAGER'],
  },

  // --- 5. PRODUCTS & CATALOG ---
  {
    code: 'PRODUCT_VIEW',
    module: 'Products',
    name: 'View Product Catalog',
    description: 'Browse product master catalog, prices, and SKU details.',
    defaultRoles: ['ADMIN', 'MANAGER', 'SUPERVISOR', 'CASHIER', 'STAFF'],
  },
  {
    code: 'PRODUCT_CREATE',
    module: 'Products',
    name: 'Create Products',
    description: 'Add new products, variants, colors, and barcode SKUs.',
    defaultRoles: ['ADMIN', 'MANAGER'],
  },
  {
    code: 'PRODUCT_EDIT',
    module: 'Products',
    name: 'Edit Products & Prices',
    description: 'Modify product pricing, descriptions, and category associations.',
    defaultRoles: ['ADMIN', 'MANAGER'],
  },
  {
    code: 'PRODUCT_DELETE',
    module: 'Products',
    name: 'Delete / Deactivate Products',
    description: 'Deactivate or delete product variants.',
    defaultRoles: ['ADMIN'],
  },

  // --- 6. INVENTORY & STOCK ---
  {
    code: 'INVENTORY_VIEW_ALL',
    module: 'Inventory',
    name: 'View Store-wide Inventory',
    description: 'View total inventory matrix, warehouse quantities, and purchase valuations.',
    defaultRoles: ['ADMIN', 'MANAGER', 'SUPERVISOR'],
  },
  {
    code: 'INVENTORY_VIEW_ASSIGNED',
    module: 'Inventory',
    name: 'View Assigned Stock',
    description: 'View stock levels for assigned department or floor category.',
    defaultRoles: ['ADMIN', 'MANAGER', 'SUPERVISOR', 'CASHIER', 'STAFF'],
  },
  {
    code: 'INVENTORY_ADJUST',
    module: 'Inventory',
    name: 'Adjust Stock Quantities',
    description: 'Perform stock adjustments, shrinkage write-offs, and audits.',
    defaultRoles: ['ADMIN', 'MANAGER'],
  },
  {
    code: 'INVENTORY_REORDER_PLAN',
    module: 'Inventory',
    name: 'Generate Reorder Plan',
    description: 'Access AI reorder planner and purchase order requisition.',
    defaultRoles: ['ADMIN', 'MANAGER'],
  },

  // --- 7. CUSTOMERS & SUPPLIERS ---
  {
    code: 'CUSTOMER_VIEW_BASIC',
    module: 'Customers',
    name: 'View Customer Details',
    description: 'Search customer name, contact phone, and loyalty balance.',
    defaultRoles: ['ADMIN', 'MANAGER', 'SUPERVISOR', 'CASHIER', 'STAFF'],
  },
  {
    code: 'CUSTOMER_VIEW_FINANCIALS',
    module: 'Customers',
    name: 'View Customer Financials',
    description: 'View customer credit limit, ledger debt, and full purchase history.',
    defaultRoles: ['ADMIN', 'MANAGER'],
  },
  {
    code: 'CUSTOMER_CREATE',
    module: 'Customers',
    name: 'Create Customer',
    description: 'Register new customers at checkout or customer directory.',
    defaultRoles: ['ADMIN', 'MANAGER', 'SUPERVISOR', 'CASHIER', 'STAFF'],
  },
  {
    code: 'SUPPLIER_VIEW',
    module: 'Suppliers',
    name: 'View Suppliers Directory',
    description: 'View textile suppliers, mills, contact information, and purchase orders.',
    defaultRoles: ['ADMIN', 'MANAGER'],
  },
  {
    code: 'SUPPLIER_MANAGE',
    module: 'Suppliers',
    name: 'Manage Suppliers & Payments',
    description: 'Create suppliers, record payments, and manage vendor accounts.',
    defaultRoles: ['ADMIN', 'MANAGER'],
  },

  // --- 8. PURCHASES & EXPENSES ---
  {
    code: 'PURCHASE_VIEW',
    module: 'Purchases',
    name: 'View Purchase Invoices (GRN)',
    description: 'View incoming supplier shipments, goods received notes, and bills.',
    defaultRoles: ['ADMIN', 'MANAGER'],
  },
  {
    code: 'PURCHASE_CREATE',
    module: 'Purchases',
    name: 'Create Purchase (GRN)',
    description: 'Record new stock inwarding and supplier purchase invoices.',
    defaultRoles: ['ADMIN', 'MANAGER'],
  },
  {
    code: 'EXPENSE_VIEW',
    module: 'Expenses',
    name: 'View Store Expenses',
    description: 'View daily operating expenses, utility bills, and petty cash.',
    defaultRoles: ['ADMIN', 'MANAGER'],
  },
  {
    code: 'EXPENSE_CREATE',
    module: 'Expenses',
    name: 'Record Store Expense',
    description: 'Record new store operational expenses.',
    defaultRoles: ['ADMIN', 'MANAGER'],
  },

  // --- 9. STAFF & HR GOVERNANCE ---
  {
    code: 'STAFF_VIEW_ALL',
    module: 'Staff',
    name: 'View Staff Directory',
    description: 'View full employee directory, designations, and department roster.',
    defaultRoles: ['ADMIN', 'MANAGER'],
  },
  {
    code: 'STAFF_MANAGE',
    module: 'Staff',
    name: 'Manage Staff Profiles',
    description: 'Add new staff, edit profile, manage documents, and assign roles.',
    defaultRoles: ['ADMIN', 'MANAGER'],
  },
  {
    code: 'ATTENDANCE_VIEW_ALL',
    module: 'Staff',
    name: 'View Store Attendance Roster',
    description: 'View daily check-ins, punctuality, and staff attendance logs.',
    defaultRoles: ['ADMIN', 'MANAGER', 'SUPERVISOR'],
  },
  {
    code: 'ATTENDANCE_VIEW_SELF',
    module: 'Staff',
    name: 'Personal Attendance & Punch',
    description: 'Punch in/out and view personal attendance history.',
    defaultRoles: ['ADMIN', 'MANAGER', 'SUPERVISOR', 'CASHIER', 'STAFF'],
  },
  {
    code: 'SHIFT_VIEW',
    module: 'Staff',
    name: 'View Shift Schedule',
    description: 'View assigned shift timings and weekly rosters.',
    defaultRoles: ['ADMIN', 'MANAGER', 'SUPERVISOR', 'CASHIER', 'STAFF'],
  },
  {
    code: 'SHIFT_MANAGE',
    module: 'Staff',
    name: 'Manage Shift Rosters',
    description: 'Assign staff to morning/evening shifts and resolve shift clashes.',
    defaultRoles: ['ADMIN', 'MANAGER', 'SUPERVISOR'],
  },
  {
    code: 'LEAVE_APPROVE',
    module: 'Staff',
    name: 'Approve Staff Leaves',
    description: 'Review and approve/reject employee leave requests.',
    defaultRoles: ['ADMIN', 'MANAGER'],
  },
  {
    code: 'PAYROLL_VIEW_ALL',
    module: 'Staff',
    name: 'View Company Payroll & Salaries',
    description: 'Access salary master, process monthly payroll, and view net pay registers.',
    defaultRoles: ['ADMIN'],
  },
  {
    code: 'PAYROLL_VIEW_SELF',
    module: 'Staff',
    name: 'View Personal Payslips',
    description: 'View personal monthly payslips and breakdown.',
    defaultRoles: ['ADMIN', 'MANAGER', 'SUPERVISOR', 'CASHIER', 'STAFF'],
  },

  // --- 10. REPORTS & BI ANALYTICS ---
  {
    code: 'REPORT_SALES_VIEW',
    module: 'Reports',
    name: 'View Sales Reports',
    description: 'Access daily, monthly, and category sales reports.',
    defaultRoles: ['ADMIN', 'MANAGER', 'SUPERVISOR'],
  },
  {
    code: 'REPORT_INVENTORY_VIEW',
    module: 'Reports',
    name: 'View Inventory Reports',
    description: 'Access fast moving, dead stock, and inventory aging reports.',
    defaultRoles: ['ADMIN', 'MANAGER', 'SUPERVISOR'],
  },
  {
    code: 'REPORT_FINANCIAL_VIEW',
    module: 'Reports',
    name: 'View Financial & Tax Reports',
    description: 'Access GST tax reports (GSTR-1/3B summaries), P&L, and gross profit breakdown.',
    defaultRoles: ['ADMIN'],
  },
  {
    code: 'REPORT_EXPORT',
    module: 'Reports',
    name: 'Export Reports',
    description: 'Export business reports to PDF, CSV, and Excel formats.',
    defaultRoles: ['ADMIN', 'MANAGER'],
  },

  // --- 11. AI & MACHINE LEARNING ---
  {
    code: 'AI_USE_ASSISTANT',
    module: 'AI',
    name: 'Use Business AI Assistant',
    description: 'Chat with AI Business Assistant for operational inquiries.',
    defaultRoles: ['ADMIN', 'MANAGER', 'SUPERVISOR'],
  },
  {
    code: 'AI_VIEW_FORECAST',
    module: 'AI',
    name: 'View AI Demand Forecasts',
    description: 'Access predictive 7/14/30-day demand and seasonal curves.',
    defaultRoles: ['ADMIN', 'MANAGER'],
  },
  {
    code: 'AI_VIEW_REORDER',
    module: 'AI',
    name: 'View AI Reorder Recommendations',
    description: 'Access automated smart reorder points and purchase suggestions.',
    defaultRoles: ['ADMIN', 'MANAGER'],
  },
  {
    code: 'AI_VIEW_ANOMALIES',
    module: 'AI',
    name: 'View AI Anomaly & Fraud Alerts',
    description: 'Access anomaly detection, stock discrepancies, and refund surge alerts.',
    defaultRoles: ['ADMIN', 'MANAGER'],
  },
  {
    code: 'AI_VIEW_RISK',
    module: 'AI',
    name: 'View AI Business Risk Matrix',
    description: 'Access business risk scores, revenue health, and operational diagnostics.',
    defaultRoles: ['ADMIN'],
  },

  // --- 12. SYSTEM ADMINISTRATION ---
  {
    code: 'ROLE_MANAGE',
    module: 'System',
    name: 'Manage Roles & Permissions',
    description: 'Create roles and customize permissions across the entire system.',
    defaultRoles: ['ADMIN'],
  },
  {
    code: 'USER_MANAGE',
    module: 'System',
    name: 'Manage User Accounts',
    description: 'Create user logins, reset passwords, and lock/unlock accounts.',
    defaultRoles: ['ADMIN'],
  },
  {
    code: 'BACKUP_MANAGE',
    module: 'System',
    name: 'Database Backup & Restore',
    description: 'Create manual database backups and restore snapshots.',
    defaultRoles: ['ADMIN'],
  },
  {
    code: 'SETTINGS_MANAGE',
    module: 'System',
    name: 'Manage Store Settings',
    description: 'Edit shop name, address, GSTIN, receipt templates, and printer preferences.',
    defaultRoles: ['ADMIN'],
  },
];

/**
 * Returns list of permission codes granted by default to a role
 */
export function getDefaultPermissionsForRole(roleName: string): string[] {
  const normalized = roleName.toUpperCase().trim();
  let targetRole: 'ADMIN' | 'MANAGER' | 'SUPERVISOR' | 'CASHIER' | 'STAFF' = 'STAFF';

  if (normalized.includes('ADMIN') || normalized.includes('OWNER') || normalized.includes('SUPER')) {
    targetRole = 'ADMIN';
  } else if (normalized.includes('MANAGER')) {
    targetRole = 'MANAGER';
  } else if (normalized.includes('SUPERVISOR') || normalized.includes('LEAD') || normalized.includes('OPS')) {
    targetRole = 'SUPERVISOR';
  } else if (normalized.includes('CASHIER') || normalized.includes('BILLING') || normalized.includes('POS')) {
    targetRole = 'CASHIER';
  }

  return PERMISSION_CATALOG
    .filter((p) => p.defaultRoles.includes(targetRole))
    .map((p) => p.code);
}

/**
 * Returns default data scope for a given role
 */
export function getDefaultDataScopeForRole(roleName: string): DataScope {
  const normalized = roleName.toUpperCase().trim();
  if (normalized.includes('ADMIN') || normalized.includes('OWNER') || normalized.includes('SUPER')) {
    return 'GLOBAL';
  }
  if (normalized.includes('MANAGER')) {
    return 'BRANCH';
  }
  if (normalized.includes('SUPERVISOR') || normalized.includes('LEAD') || normalized.includes('OPS')) {
    return 'DEPARTMENT';
  }
  if (normalized.includes('CASHIER') || normalized.includes('BILLING') || normalized.includes('POS')) {
    return 'SELF';
  }
  return 'ASSIGNED';
}
